/**
 * DB Schema of Project Bank.
 * MySQL e Cloudscape (for J2EE)
 */

CREATE SCHEMA BANK_DB;

USE BANK_DB;

CREATE TABLE AGENCY
(
	AGENCY_NUMBER INT PRIMARY KEY,
	ADDRESS VARCHAR(200)
);

CREATE TABLE ACCOUNT
(
	AGENCY_NUMBER INT NOT NULL,
	ACCOUNT_NUMBER INT NOT NULL UNIQUE,
	NAME VARCHAR(100) NOT NULL,
	BALANCE DECIMAL(10,2) NOT NULL,
	PRIMARY KEY(AGENCY_NUMBER, ACCOUNT_NUMBER),
	FOREIGN KEY(AGENCY_NUMBER) REFERENCES AGENCY(AGENCY_NUMBER)
);

CREATE TABLE DEPOSIT
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	AGENCY_NUMBER INT NOT NULL,
	ACCOUNT_NUMBER INT NOT NULL,
	DATE_DEPOSIT DATE,
	AMOUNT DECIMAL(10,2),
	NAME VARCHAR(200),
	FOREIGN KEY(AGENCY_NUMBER,ACCOUNT_NUMBER) REFERENCES ACCOUNT(AGENCY_NUMBER,ACCOUNT_NUMBER)
);

CREATE TABLE WITHDRAW
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	AGENCY_NUMBER INT NOT NULL,
	ACCOUNT_NUMBER INT NOT NULL,
	DATE_WITHDRAW DATE,
	AMOUNT DECIMAL(10,2),
	FOREIGN KEY(AGENCY_NUMBER,ACCOUNT_NUMBER) REFERENCES ACCOUNT(AGENCY_NUMBER,ACCOUNT_NUMBER)
);

INSERT INTO AGENCY VALUES(210419,'Johnson Smith Avenue'),(299012,'Morpheus Avenue'),(299911,'Washington Avenue');
INSERT INTO ACCOUNT VALUES(299012,5365854,'Wesley Egberto', 1000.0);


select * from AGENCY;

select * from ACCOUNT;

select * from WITHDRAW;
